# Generated by Django 4.2.7 on 2023-11-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenditures", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenditure",
            name="is_except",
            field=models.BooleanField(default=False),
        ),
    ]
